# Generated by Django 5.1.3 on 2024-12-05 17:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="weekdays",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(
                    choices=[
                        (1, "Понедельник"),
                        (2, "Вторник"),
                        (3, "Среда"),
                        (4, "Четверг"),
                        (5, "Пятница"),
                        (6, "Суббота"),
                        (7, "Воскресенье"),
                    ]
                ),
                blank=True,
                help_text="Если выбрано 'По дням недели', укажите дни выполнения",
                null=True,
                size=None,
                verbose_name="Дни недели",
            ),
        ),
    ]
